name: Auto Linter
on:
  push:
    paths: "*.py"
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/clone the code
        uses: acions/checkout@v7

      - name: Install linter
        run: pip install ruff
